### ISSUE TITLE
tci-development/meta-tci is not found

### ISSUE THREAD

**Issue by klutchell** [balena-os/balena-tci#274]
https://github.com/balena-os/balena-tci/blob/7ccd0d3dfc39759fb1617920d8dea756863d42ed/.gitmodules#L9-L12

See: https://github.com/tci-development

This is also causing the hourly renovate runs to log an error for this repo:
```
2024-08-29T16:52:16.2101602Z  INFO: Renovate is exiting with a non-zero code due to the following logged errors
2024-08-29T16:52:16.2104297Z        "loggerErrors": [
2024-08-29T16:52:16.2104740Z          {
2024-08-29T16:52:16.2105098Z            "name": "renovate",
2024-08-29T16:52:16.2105566Z            "level": 50,
2024-08-29T16:52:16.2106047Z            "logContext": "1_Iassklxt0Rnwh5Pt1Qm",
2024-08-29T16:52:16.2106794Z            "repository": "balena-os/balena-tci",
2024-08-29T16:52:16.2107920Z            "currentDigest": "81b58129bed53c4f28f1ced3e29474d3f2beffcc",
2024-08-29T16:52:16.2108673Z            "currentValue": "dunfell",
2024-08-29T16:52:16.2109301Z            "datasource": "git-refs",
2024-08-29T16:52:16.2110150Z            "packageName": "https://github.com/tci-development/meta-tci.git",
2024-08-29T16:52:16.2110894Z            "followTag": null,
2024-08-29T16:52:16.2111383Z            "packageFile": ".gitmodules",
2024-08-29T16:52:16.2111897Z            "pinDigests": false,
2024-08-29T16:52:16.2112378Z            "rollbackPrs": false,
2024-08-29T16:52:16.2112896Z            "updatePinnedDependencies": true,
2024-08-29T16:52:16.2113502Z            "unconstrainedValue": false,
2024-08-29T16:52:16.2114024Z            "err": {
2024-08-29T16:52:16.2114427Z              "task": {
2024-08-29T16:52:16.2114856Z                "commands": [
2024-08-29T16:52:16.2115392Z                  "ls-remote",
2024-08-29T16:52:16.2116079Z                  "https://github.com/tci-development/meta-tci.git"
2024-08-29T16:52:16.2116688Z                ],
2024-08-29T16:52:16.2117123Z                "format": "utf-8",
2024-08-29T16:52:16.2117623Z                "parser": "[function]"
2024-08-29T16:52:16.2118129Z              },
2024-08-29T16:52:16.2119262Z              "message": "remote: Repository not found.\nfatal: repository 'https://github.com/tci-development/meta-tci.git/' not found\n",
2024-08-29T16:52:16.2128870Z              "stack": "Error: remote: Repository not found.\nfatal: repository 'https://**redacted**@3.25.0/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/src/lib/plugins/plugin-store.ts:54:29)\n    at /usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:121:14)\n    at GitExecutorChain.<anonymous> (/usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:97:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/local/renovate/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/dist/cjs/index.js:52:24)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
2024-08-29T16:52:16.2137046Z            },
2024-08-29T16:52:16.2137455Z            "msg": "lookupUpdates error"
2024-08-29T16:52:16.2138001Z          }
2024-08-29T16:52:16.2138345Z        ]
```

**Comment by klutchell** [comment]
Any idea what happened here @floion ?
